### ISSUE TITLE
Add compatibility for adding link to "Anchor on a page" in WYSIWYG editors

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-elemental#186]
![image](https://user-images.githubusercontent.com/5170590/36079567-34aa58d6-0fe9-11e8-8166-66fe7baa1b6c.png)

This functionality in the CMS lets you add a link to an anchor on an arbitrary page. With elemental enabled on a page this won't automatically populate a list of available anchors, since it'll be reading and parsing the page's Content field.

If we can augment the search location for HTML then we can tie it into the method that returns an entire page's elemental content for the sake of search indexing (see #163).

From a data point of view we definitely want to avoid duplicating all element data into the page's Content field.

Note that currently a WYSIWYG inside an elemental block is able to link to anchors within itself, but not within other elemental blocks on the same or on other blocks. On save, these links get marked as broken, even though they work.

## Acceptance Criteria
- [x] Using the "anchor on a page" link in a WYSIWYG field (either directly on a page or inside an elemental block), I can link to anchors inside elemental blocks on _a different_ page
- [x] Using the "anchor on a page" link in a WYSIWYG field, I can link to anchors inside the same elemental block I am editing
- [x] Using the "anchor on a page" link in a WYSIWYG field, I can link to anchors inside _other_ elemental blocks on _the same_ page
- [x] Links to anchors inside elemental blocks are not marked as broken
- [x] Links to anchors that do not exist on the page or in any elemental blocks _are_ marked as broken

## PRs
- #911 
- https://github.com/silverstripe/silverstripe-cms/pull/2741
- https://github.com/silverstripe/silverstripe-frameworktest/pull/106
- https://github.com/silverstripe/silverstripe-cms/pull/2742

**Comment by brynwhyman** [comment]
Thinking a higher level API would be required for this. There's a number of modules that would also be affected by this too: `externallinks`, `fulltextsearch`, maybe more?

**Comment by MichelleZZZZ** [comment]
Hi @robbieaverill 

I have a similar issue with Anchor on the Elemental block(not inline form). And I would like to ask if the fix might happen at some stage?

Cheers

**Comment by robbieaverill** [comment]
Hi @MichelleZZZZ, I'm not sure what the roadmap looks like but @brynwhyman may be able to help

**Comment by GuySartorelli** [comment]
Looks like this would be fixed by #911
