### ISSUE TITLE
Deleting element via gridfield delete action doesn't archive the element

### ISSUE THREAD

**Issue by nyeholt** [silverstripe/silverstripe-elemental#212]
If you use the gridfield Delete action (either at the element area level or in an element list) the element is removed from the base Element table, but not the Element_Live table, meaning floating, unremoveable elements displaying. 

Repro

* Add an element to an element area / element list
* Save / publish the element. Confirm entries in both Element and Element_Live tables
* Go to the parent gridfield view
* Click the 'delete' icon
* Confirm the element has been deleted from Element table, but still remains in Element_Live

SS 4.1, Elemental ~2.0 (have tested with master branch and still an issue).

**Comment by robbieaverill** [comment]
Re-test once #217 is implemented which uses more of the $owns API from SS 4.1

**Comment by GuySartorelli** [comment]
The UI for elemental blocks has changed substantially since this issue was raised, and the behaviour as described no longer applies.
