### ISSUE TITLE
Some of the "More Actions" should still show on non in-line editable blocks

### ISSUE THREAD

**Issue by ScopeyNZ** [silverstripe/silverstripe-elemental#512]
### Affected Versions

4.x

### Description

When a block is _not_ in-line editable it still makes sense for some actions to exist:

- Publish
- Unpublish
- Archive

### Steps to reproduce

- Create a non in-line editable block type (or install one like `dnadesigns/silverstripe-elemental-userforms`)
- Add that block type to an elemental area
- Observe there's no "More actions" menu

## Designs

See block basics designs https://projects.invisionapp.com/dsm/silver-stripe/silverstripe-cms/nav/5fa7cb5f8c012000183561a5/asset/607e6266ade40316eb2697ee/tab/design?mode=preview

## ACs
- Confirm the final list of actions to be included in the list (note to not include the 'tabs' like Content and Settings)
  - Ensure that the new 'Duplicate' action is present in the list (https://github.com/silverstripe/silverstripe-elemental/issues/881)
- The finalised list of actions are implemented
- Ensure that the status icons on the block reflect any action made, i.e publishing the block updates the status icon
- Close this https://github.com/silverstripe/silverstripe-elemental/issues/881

### PRs
- [ ] ~~https://github.com/silverstripe/silverstripe-elemental/pull/925~~
- [ ] https://github.com/silverstripe/silverstripe-elemental/pull/963

**Comment by robbieaverill** [comment]
Do we have designs with the `>` caret _and_ the dropdown? I don't remember seeing anything

**Comment by ScopeyNZ** [comment]
I think the original designs didn't have the "meatballs" on non in-line editable blocks. But I also remember us discussing this a few weeks ago and noting it'd be a UX improvement. Worth tracking at least :slig

**Comment by robbieaverill** [comment]
Ok cool. This is probably one of those options where the UX team popping down while we design on the fly would be the easiest solution, but for the sake of open source perhaps @sachajudd you could provide a quick design mockup of what you want it to look like in case a community member wants to pick this up before we get to it

**Comment by sachajudd** [comment]
See collapsed [dnadesigns/silverstripe-elemental-userforms](https://projects.invisionapp.com/dsm/silver-stripe/silver-stripe/asset/components/5bda2b9c9029b00017b97a65) block.

**Comment by chillu** [comment]
+1, just come across this as well.

**Comment by clarkepaul** [comment]
Related, adding duplicate blocks to non-inline blocks https://github.com/silverstripe/silverstripe-elemental/issues/881

**Comment by clarkepaul** [comment]
With non-inline blocks being still in relatively high use, providing this set of actions seems like a good first step. I'm increasing the impact as going in and pout of blocks to preform basic actions would be frustrating to say the least.

**Comment by emteknetnz** [comment]
Linked PR has been merged
