### ISSUE TITLE
Insert all link types from the link component

### ISSUE THREAD

**Issue by sachajudd** [silverstripe/silverstripe-elemental#589]
A user should be able to insert all link types from the link component e.g the banner block. Currently the only option is linking to a page on the site:
![image](https://user-images.githubusercontent.com/24258161/50748818-16e9d000-12a0-11e9-9432-485f0da498cf.png)

After some consideration we have decided to slightly redesign the link component to cater for these options. See the [Styleguide](https://projects.invisionapp.com/dsm/silver-stripe/silver-stripe/asset/components/5c4e6d24f3ad3830147691f6) **for the new designs**. Unsure if this link component should be moved into core? cc @robbieaverill 

* The component is to borrow the same dropdown component from the TinyMCE insert link option.
* Remove "Changes will be visible upon save" (if possible) after saving link details as "Link title" and "URL" should be present after inserting:
Current CMS link component: ![image](https://user-images.githubusercontent.com/24258161/51808426-79127f80-22f8-11e9-9143-450c558392b0.png)
* Link fields to be reordered so 'Link text' appears first.
* Note: text-muted for "Link type" text.
* @clarkepaul recalls that the "Anchor from a page" option in the TinyMCE dropdown was added as there were limitations to being able to combine "Page on this site" and "Anchor on a page" together. See https://github.com/silverstripe/silverstripe-cms/issues/2379 for more details of removing the anchor dropdown option and the new modal designs.

**Comment by robbieaverill** [comment]
> After some consideration we have decided to slightly redesign the link component to cater for these options. See the Styleguide for new designs. Unsure if this link component should be moved into core? cc @robbieaverill

See https://github.com/silverstripe/silverstripe-elemental-bannerblock/issues/10

**Comment by chillu** [comment]
I've created a wider discussion on how to proceed with this in terms of a reuseable link moudle: https://forum.silverstripe.org/t/new-links-module/1642

**Comment by maxime-rainville** [comment]
We won't be putting any effort into this given that we are about to ship linkfield.
