### ISSUE TITLE
Should upgrading the module (or adding new elemental areas) republish pages? 

### ISSUE THREAD

**Issue by michalkleiner** [silverstripe/silverstripe-elemental#687]
The title is quite broad, but best describes the problem we have. Upgrading Elemental from 1.9 to 3 (or 4), changing how the ElementalArea is added to a page.

Because of how `requireDefaultRecords()` works in https://github.com/dnadesign/silverstripe-elemental/blob/47ee8710488f9819c98dbd6b5306bb1ac6797277/src/Extensions/ElementalAreasExtension.php#L274, all holding pages/dataobjects using the `ElementalAreasExtension` get new Draft and Published versions created by simply running `dev/build`.

This is a problem when surfacing LastEdited date on the frontend as all dates change to the time of running the first dev/build triggering the method above.

It might be even for a wider framework-level discussion, but as this is currently our pain point, raising it here. It may affect other developers/users upgrading Elemental during their SS4 upgrade.

Our view is that CMS editor created already existing data should stay untouched through an upgrade with the exception of, of course, creating new models that didn't exist before.

**Comment by ScopeyNZ** [comment]
Yeah I think this is a pretty legitimate bug. Should be relatively easy to avoid the write (and publish) if the elemental area doesn't exist. I think this part of the code could do with some love also, see related PR: #671.

**Comment by robbieaverill** [comment]
We could use writeWithoutVersion() as well to avoid new versions being created here. Auto publishing the page seems valid provided the page was previously in a published state and writeWithoutVersion() doesn’t propagate to the live stage immediately.

**Comment by GuySartorelli** [comment]
@michalkleiner I'm guessing this isn't relevant anymore, but wanted to just double check with you before closing.

**Comment by michalkleiner** [comment]
Probably isn't as it was related to SS 3 to 4 migration. Haven't checked/heard whether 4 to 5 behaves the same but for now this can be closed and we can reopen/create a new issue when needed.
