### ISSUE TITLE
CMS users lose all blocks when attempting to save page with validation errors

### ISSUE THREAD

**Issue by scott1702** [silverstripe/silverstripe-elemental#764]
## Overview

This may be more of a framework issue than an elemental issue, but haven't investigated enough to know.

When users attempt to save/publish a page, if the page has any validation errors then any content blocks which have been created get entirely removed as the page fails to save. This can be especially frustrating if there are required fields in other tabs which the user hasn't seen yet.

## Steps to reproduce:
- Create a page with required fields and an elemental area
- Fill out the page with numerous content blocks and leave the required field empty
- Save and/or publish the page

### Actual result:

- The content blocks are removed as the page has failed to save due to validation error

### Expected result:

- The content blocks are retained in an unsaved state, in the same manner as other fields

## Acceptance Criteria

* When a validation error against a _Page-level_ field is returned from attempting to save / publish the page, blocks and their unsaved contents are retained in the editor.
* When a validation error against a _Block-level_ field is returned from attempting to save / publish the page, blocks and their unsaved contents are retained in the editor.

## Out of scope

- [ ] Validation errors are displayed next to the elemental block - should be covered in the following: https://github.com/silverstripe/silverstripe-elemental/issues/329

## Notes

- We have some old PR that might fix this issue. If they don't fix the issue and are not salvageable, bring the card back into refinement.

## PRs
- https://github.com/silverstripe/silverstripe-admin/pull/1246
- https://github.com/silverstripe/silverstripe-elemental/pull/930

**Comment by ScopeyNZ** [comment]
@brynwhyman I was torn between `impact/high` and `impact/critical` here - feel free to re-adjust.

This doesn't surprise me, but it's obviously a bad bug. We had to work around the fact that SilverStripe replaces the whole form when saving with our new React editor. Redux should remember all of the form data, but it might be getting cleared on the response from the server, regardless of whether it was successful or not. I wonder if this can be _relatively_ easily fixed by selectively clearing redux here:

https://github.com/dnadesign/silverstripe-elemental/blob/4/client/src/legacy/ElementEditor/entwine.js#L72

**Comment by GuySartorelli** [comment]
In my recent experience with version 4.4.0, the blocks themselves remain but the content within the block is cleared.

**Comment by chrispenny** [comment]
It's worth mentioning that you will also experience the same thing if you apply validation requirements to an Element through the `validate()` extension point.

EG, I use the following `addFieldError()` method:
```
$validationResult->addFieldError('MyField', 'Required');
```

If I click "Save" in the inline editor, I get the following popup (but nothing in the inline editor):
![Screen Shot 2020-11-20 at 7 41 56 AM](https://user-images.githubusercontent.com/505788/99709371-f9285b80-2b03-11eb-9819-da184abff5c0.png)

If I click "Save" on the page, my edits in the Element are lost, and this message is displayed in my Page edit form:
![Screen Shot 2020-11-20 at 7 43 52 AM](https://user-images.githubusercontent.com/505788/99709585-43a9d800-2b04-11eb-8486-3bfaa66d1f77.png)

This is likely related to this open ticket as well:
https://github.com/dnadesign/silverstripe-elemental/issues/329

As it seems that validation requirements that are specified in an Element's `getCMSValidator()` or (the new) `getCMSCompositeValidator()` are also not respected.

I think at the moment we have no way to reasonably provide validation requirements if we're using inline editing? Someone please, please correct me if I'm wrong.

**Comment by GuySartorelli** [comment]
PRs merged. In the process of merging up between majors, then I'll tag.

**Comment by GuySartorelli** [comment]
Tagged for CMS 4 (update `silverstripe/admin` to 1.13.2 and `dnadesign/silverstripe-elemental` to 4.13.1)
CMS 5.0 ran into an error after merge-up so that will need to be handled separately.

In any case, this card can now be closed, as the work directly related to it is complete.

**Comment by GuySartorelli** [comment]
This has now also been tagged for CMS 5 - update `silvertripe/admin` to 2.0.1 and `dnadesign/silverstripe-elemental` to 5.0.1
