### ISSUE TITLE
Upon converting a page to a "Block Page" automatically create Content block with existing content

### ISSUE THREAD

**Issue by purplespider** [silverstripe/silverstripe-elemental#767]
Often a CMS user may have a basic `Page` with some simple content in the Content area.

At some point, they may then wish to convert this `Page` to a `Blocks Page` in order to add extra elements.

However, when they do this, all existing content is removed without warning. Not a great user experience. Many users won't know that reverting the page to a `Page` will bring back the content. 

Perhaps, upon the change of type to a `Block Page`, it could automatically create a `Content` **block** containing all the initial content fro the original page's `Content` **field**. Then the CMS user is free to add more blocks, and edit or remove the original content as they wish.

**Comment by ScopeyNZ** [comment]
We already have a task that does this:

https://github.com/dnadesign/silverstripe-elemental/blob/4/src/Tasks/MigrateContentToElement.php

Perhaps we can move the relevant logic to a standalone service and then use it both in the task and some hook on conversion to a block page?

I'd be happy to review a PR if you feel up to it?

**Comment by purplespider** [comment]
Can be achieved with a simple addition to `onAfterWrite()` on your "BlocksPage" (which isn't included in the Elemental module, so I won't worry about a PR):

````php
<?php

namespace PurpleSpider\MySite;

use Page;
use DNADesign\Elemental\Models\ElementContent;
use DNADesign\Elemental\Extensions\ElementalPageExtension;

class BlocksPage extends Page {

    private static $table_name = 'BlocksPage';
    private static $description = 'A modular page composed of content blocks';
    private static $icon_class = 'font-icon-p-alt-2';

    private static $extensions = [
        ElementalPageExtension::class,
    ];

    public function onAfterWrite()
    {
        // If just converted: copy any Content to a new Content block
        if($this->Content) {
            if($area = $this->ElementalArea()) {
                if(!$area->Elements()->exists()) {
                    $element = ElementContent::create();
                    $element->ParentID = $area->ID;
                    $element->Title = "Content";
                    $element->HTML = $this->Content;
                    $element->write();
                }
            }
        }

        parent::onBeforeWrite();
    }

}
````
