### ISSUE TITLE
Cannot link to another blocks anchors

### ISSUE THREAD

**Issue by StephenMakrogianni** [silverstripe/silverstripe-elemental#796]
### Issue:
In the WYSIWYG editor, content authors cannot link to another blocks anchors.

### Proposed solution
- Create a hook or move existing hook on `SiteTree::getAnchorsOnPage()` and update the list with the selected page's anchors categorized by the Elemental block they are in. 

- Change how the list is displayed to something similar to the tree drop down field where the content author could select the Elemental block to anchor to or one of it's "children" (anchors in the WYSIWYG).

**Note**: 
I have started working on the solution and am taking the following into consideration:
- Multiple `EementalArea` on a single page
- Multiple `HTMLText` fields on an Element
- Making this an optional configuration
- A setting to make the Element undiscoverable 
- An optional name to be used as the id of the Element. Will fallback to the Title or generate UID if Title is unset
- Ensure anchor link doesn't display as broken in WYSIWYG.

Anything else put it in a comment.

### Related
https://github.com/silverstripe/silverstripe-elemental/issues/894

### PRs
- [ ] https://github.com/silverstripe/silverstripe-cms/pull/2675
- [ ] https://github.com/silverstripe/silverstripe-elemental/pull/911

**Comment by mfendeksilverstripe** [comment]
I suggest to use [getUniqueKey()](https://github.com/silverstripe/silverstripe-framework/blob/4/src/ORM/DataObject.php#L4203) to generate the anchor IDs.

**Comment by StephenMakrogianni** [comment]
Nice one @mfendeksilverstripe 👍 will do.

**Comment by brynwhyman** [comment]
Hey @StephenMakrogianni how have you been getting on with a solution here?

**Comment by StephenMakrogianni** [comment]
@brynwhyman haven't had a chance to get to it yet mate. Hack day is coming up though so might give it a nudge then

**Comment by GuySartorelli** [comment]
The root problem here is that anchors inside an elemental block are not properly supported. This will be resolved with #186, so I'm closing this issue in favour of that one.
