### ISSUE TITLE
Can't nest Elemental Areas

### ISSUE THREAD

**Issue by adrhumphreys** [silverstripe/silverstripe-elemental#824]
Alright, so there's the dream of a "Layout block" which would contain an ElementalArea with inline editing, etc

To start on this dream we create a `LayoutBlock` which extends `BaseElement`.
We set it up to have a `has_one` to `ElementalArea`, and assign the extension `ElementalAreasExtension`

From here we will get some errors when trying to inline edit the LayoutBlock, this is because the `ElementalAreaField` doesn't define it's `$schemaComponent = 'ElementEditor'` and `$schemaDataType = FormField::SCHEMA_DATA_TYPE_CUSTOM`.

So we assign those and then we get our next set of errors, this is the state of `ElementEditor` not being complete since we set part of the state in the entwine bundle.

We can then update `getSchemaDataDefaults` like so (this has been applied to a class extending `ElementalAreaField` but can be applied to the original field too):
```php
public function getSchemaDataDefaults()
{
    $schemaData = parent::getSchemaDataDefaults();

    $schemaData['fieldName'] = $this->getName();
    $schemaData['areaId'] = $schemaData['elemental-area-id'];
    $schemaData['allowedElements'] = $schemaData['allowed-elements'];
    $schemaData['elementTypes'] = ElementTypeRegistry::generate()->getDefinitions();

    return $schemaData;
}
```

Alright, we have the correct state and now the field is loading as expected.
We can click to edit blocks, add blocks, etc

<img width="227" alt="image" src="https://user-images.githubusercontent.com/10803137/90308552-7efc9f80-df34-11ea-949c-9451ab0b937d.png">

If we select the menu for the newly added block and click save/publish/etc it will save assigned to the layout block as expected.

The new issue is adding/editing a block and then clicking save/publish on the page

The error you get is in `ElementalAreaField::setSubmittedValue` as we now pass through multiple layout areas to the field

This is the data being loaded into the field:
```json
{
  "ElementForm_2": {
    "Root": null,
    "Main": null,
    "Title": null,
    "PageElements_2_Title": "Layout+one?",
    "PageElements_2_ShowTitle": 0,
    "PageElements_2_AbsoluteLink": null,
    "PageElements_2_LiveLink": "http://layout.test/#e2",
    "PageElements_2_StageLink": "http://layout.test/home/?ElementalPreview=1435203022#e2",
    "PageElements_2_LayoutAreaID": 7,
    "Settings": null,
    "PageElements_2_ExtraClass": null,
    "History": null,
    "PageElements_2_ElementHistory": null,
    "PageElements_2_SecurityID": "89990836978d63d4dd74ef76adc6cd728c5f292e",
    "SecurityID": "89990836978d63d4dd74ef76adc6cd728c5f292e"
  },
  "ElementForm_9": {
    "Root": null,
    "Main": null,
    "Title": null,
    "PageElements_9_Title": "Testing123",
    "PageElements_9_ShowTitle": 0,
    "PageElements_9_HTML": null,
    "PageElements_9_AbsoluteLink": null,
    "PageElements_9_LiveLink": "http://layout.test/",
    "PageElements_9_StageLink": "http://layout.test/",
    "Settings": null,
    "PageElements_9_ExtraClass": null,
    "History": null,
    "PageElements_9_ElementHistory": null,
    "PageElements_9_SecurityID": "89990836978d63d4dd74ef76adc6cd728c5f292e",
    "SecurityID": "89990836978d63d4dd74ef76adc6cd728c5f292e"
  }
}
```

Somehow the state of the nested elemental area is being combined with the main elemental area. The submitted Form value which contains this is `ElementalArea` and out nested `LayoutBlock` has the value `PageElements_2_LayoutAreaID` set to the same value as `ElementalArea`

If we could resolve this issue, from what I can see we would be well placed to nest elemental areas and allow for the creation of a layout block.

Here's a gist for reproducing the issue: https://gist.github.com/adrhumphreys/3a1a8fed76db6f2999f1d0e815df3339
The `LayoutBlock` in this gist just reimplements `ElementalAreasExtension` but with a different relation name to test if it was something weird going on there (there wasn't)

I also edited `ElementalAreaField.php::235` from: `if (!$elementData)` to:`if (!$elementData || !is_array($elementData))`. This is because `saveInto` was being called for the LayoutBlock and due to the weird state was being set to it's ID

So since you're passed both lists of data in the one field you can actually just loop through both lists in `ElementalAreaField::saveInto` and by updating the line:  
`$element = $this->getArea()->Elements()->byID($elementId);`
to:  
`$element = BaseElement::get_by_id($elementId);`  
It will now pick up all elements and update them as you'd expect

I feel like updating the code to do this is probably not the best idea and really the data being sent that represents both the ElementalArea's should be nested which would remove the need to update these functions

I'm not sure what is causing the combination though, some thoughts/ideas:
- The are being combined due to the redux state management causing
- The form builder HOC doesn't know how/that it should split them
- The `ElementEditor` is tightly coupled to the page in some way

**Comment by tractorcow** [comment]
Have you tried out https://github.com/dnadesign/silverstripe-elemental-list which solves some of these issues.

I agree that the tight coupling to a page is an issue, and should be addressed at some point in the core, but the list module does work around this issue.

**Comment by adrhumphreys** [comment]
I've had a look into that module and sadly they just gave up on inline editing entirely for it so you end up needing to create a layout block which has no actions in it. You then need to click onto that newly created block to then be able to add blocks inside of it. This proves to be a very awkward content author experience.

**Comment by tractorcow** [comment]
Ah right, you can't inline edit inside another inline parent, but you can inline edit inside a non-inline parent. :)

I agree it's a sub-perfect solution, but maybe one day there'll be a fully dynamic inline solution.

I suggested in another ticket that you could use something like a userforms-like solution in order to nest items (groups have a draggable start / stop line you can use to manually group items).
