### ISSUE TITLE
Media insertion from a link doesn't seem to work properly

### ISSUE THREAD

**Issue by J-Pielage** [silverstripe/silverstripe-elemental#828]
I created my own BaseElement, added a HTMLEditorField and use the option to insert media via a link.
At first insertion seems okay, but saving or publishing removed the insertion. I've created a screencapture to show the issue.

![ezgif com-optimize](https://user-images.githubusercontent.com/25040417/91185135-ba922900-e6ed-11ea-825f-f86655f10603.gif)

**Comment by kinglozzer** [comment]
Hi @J-Pielage, can you share the code for your element?

**Comment by J-Pielage** [comment]
looks like this:

`<?php

use SilverStripe\CMS\Model\SiteTree;

use DNADesign\Elemental\Models\BaseElement;

use SilverStripe\Forms\TextField;
use SilverStripe\Forms\HTMLEditor\HTMLEditorField;
use SilverStripe\Forms\TreeDropdownField;
use SilverStripe\Forms\DropdownField;

use SilverStripe\Assets\Image;
use SilverStripe\AssetAdmin\Forms\UploadField;

class ContentBlock extends BaseElement {
	private static $singular_name = 'Content';
	private static $description = 'Content blok';
	private static $inline_editable = false;
	private static $icon = 'font-icon-block-content';
  private static $controller_template = 'CustomElementHolder';

	private static $db = [
    'Title'             => 'Varchar',
    'Text'              => 'HTMLText',
	];
	

	public function getCMSFields(){     
		$fields = parent::getCMSFields();

    $fields->addFieldsToTab('Root.Main', [
      TextField::create('Title', 'Titel'),
      HTMLEditorField::create('Text', 'Tekst')->setRows(20),
    ]);

		return $fields;
  }

	public function getType() {
		return 'Content';
	}
}`

**Comment by dnsl48** [comment]
Hi @J-Pielage, could you please also provide the following info:
 - Silverstripe CMS Recipe version
 - Browser
 - PHP version, Operating System
 - installed SilverStripe modules

**Comment by J-Pielage** [comment]
I use the following setup:

- Google Chrome version 83.0.4103.116
- Silverstripe recipe: "silverstripe/recipe-cms": "4.6.*@stable", 
- MacOS 10.15.6
- PHP version 7.3.9

This is the list of modules that are being used:
```
"require": {
        "php": ">=7.1.0",
        "silverstripe/recipe-plugin": "^1.2",
        "silverstripe/recipe-cms": "4.6.*@stable",
        "jonom/focuspoint": "^3.1",
        "dnadesign/silverstripe-elemental": "^4",
        "cyber-duck/silverstripe-seo": "4.2.*",
        "wilr/silverstripe-googlesitemaps": "^2.1",
        "silverstripe/redirectedurls": "dev-master",
        "kinglozzer/silverstripe-tinypng": "^3.0",
        "stevie-mayhew/silverstripe-svg": "^2.2",
        "undefinedoffset/sortablegridfield": "^2.0",
        "sheadawson/silverstripe-shortcodable": "4.0.x-dev",
        "silverstripe/userforms": "^5.5",
        "derralf/silverstripe-mobiledetect": "^1.0@dev",
        "heyday/silverstripe-menumanager": "~3.0.0",
        "colymba/gridfield-bulk-editing-tools": "^3.0"
    },
```

**Comment by emteknetnz** [comment]
I could not replicate this issue with framework 4.11.x-dev and elemental 4.9.x-dev.  Please let me know if you are still experiencing this issue
