### ISSUE TITLE
Default Type for BaseElement

### ISSUE THREAD

**Issue by mfendeksilverstripe** [silverstripe/silverstripe-elemental#831]
# Default Type for BaseElement

Current Type default for is as follows:

```
_t(__CLASS__ . '.BlockType', 'Block');
```

This often requires Blocks to define their own `getType()` method which seems unnecessary in most cases.

## Suggested change

Use  a good default  for type, ideally this can work out of the box - without the need to define   `getType()` method on blocks. Edge cases can be handled by configuration API.

## Solution

https://github.com/dnadesign/silverstripe-elemental/pull/830

**Comment by alex-dna** [comment]
This dosen't work, because in `_t(__CLASS__ . '.BlockType', 'Block');` , `__CLASS__` doesn't seem to cascade down on subclass.Perhaps best to use `get_class` or `static::class`?

**Comment by christopherdarling** [comment]
Made a PR pretty much as suggested above by @alex-dna https://github.com/silverstripe/silverstripe-elemental/pull/1134

**Comment by GuySartorelli** [comment]
PR has been merged - this will be available in CMS 5.2, which will be released in April
