### ISSUE TITLE
Elementals are duplicable when canCreate() is false

### ISSUE THREAD

**Issue by Jianbinzhu** [silverstripe/silverstripe-elemental#857]
When elementals are not meant to be creatable, but they are still duplicable. We have a content block that is created on page creation, and we made that content block `canCreate()` return `false`, but the duplicate option is still duplicating the content block. Is there a workaround this by hiding the duplicate action?

PR (now closed): https://github.com/dnadesign/silverstripe-elemental/pull/859

### PR
- [x] https://github.com/dnadesign/silverstripe-elemental/pull/877

**Comment by emteknetnz** [comment]
Not that I'm aware of sorry.  

Could I just get you to check something?  After you duplicate an element, if you refresh the page is it still there?

I'm just wondering if there's something odd happening where doWrite = false
https://github.com/dnadesign/silverstripe-elemental/blob/4.5/src/GraphQL/DuplicateElementMutation.php#L62
https://github.com/silverstripe/silverstripe-framework/blob/4/src/ORM/DataObject.php#L505

**Comment by scott1702** [comment]
> Could I just get you to check something? After you duplicate an element, if you refresh the page is it still there?

Yep the element is still there

**Comment by emteknetnz** [comment]
PR https://github.com/dnadesign/silverstripe-elemental/pull/877

**Comment by Cheddam** [comment]
Fixed in #877.
