### ISSUE TITLE
Elemental Area can be added to a non-Page DataObject and edited in a ModelAdmin

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-elemental#871]
[`BaseElement::CMSEditLink`](https://github.com/dnadesign/silverstripe-elemental/blob/4/src/Models/BaseElement.php#L707) assumes that blocks are attached to an Object with a `CMSEditLink` wethod. So when an `ElementalArea` is added to a `DataObject` edited via a ModelAdmin, you'll get this error `Object->__call(): the method 'CMSEditLink' does not exist on 'SilverStripe\\FrameworkTest\\Model\\Company'`

# Acceptance Criteria
- [x] Elemental Area can be added to DataObjects that are not sub classes of SiteTree
- [x] Proper guidance is given to developers on how to add an Elemental Area to a plain DataObject
- [x] Either developers have to define their own `CMSEditLink` method or we come with a way to "guess" the edit link

# Stretch goal
- Create a generic reusable API to define what ModelAdmin should be use to edit a DataObject and create the CMSEditLink from that.

# Notes
There was some recent work to allow previews to be added to ModelAdmin. Ideally, tho solution to this card should work with tho preview as well.

## PRs
- silverstripe/silverstripe-elemental#978
- #982
- https://github.com/silverstripe/silverstripe-frameworktest/pull/105

**Comment by maxime-rainville** [comment]
Off the top of my head, I'm thinking we could
- update `BaseElement::CMSEditLink` to return `null` when the `ElementalArea is attached to an object without a `CMSEditLink` method.
- Implement a way for a DataObject to explicitly say, "go through this ModelAdmin to edit me"

**Comment by brynwhyman** [comment]
Related/ duplicate: https://github.com/silverstripe/silverstripe-elemental/issues/718

**Comment by GuySartorelli** [comment]
Possibly related: #965

**Comment by sabina-talipova** [comment]
I suggest to add a few changes in the CMSEditLink() method in class BaseElement class. 
```
        if (!$page instanceof SiteTree) { 
            if (method_exists($page, 'CMSEditLink')) {
                $link = Controller::join_links($page->CMSEditLink(), 'ItemEditForm');
            } else {
                $link = null;
                $this->extend('updateCMSEditLink', $link);
                return $link;
            }
        } else {
            $link = $page->CMSEditLink();
        }

```

**Comment by sabina-talipova** [comment]
I'm going to provide an instruction how to use Elemental Area in DataObject and how to display Elements on a Page in section ["Model and DataBases. How To's " in Developer Guides ](https://docs.silverstripe.org/en/4/developer_guides/model/how_tos/)

**Comment by maxime-rainville** [comment]
Looks good ... I think those suggested improvement are a nice touch. When checking if a object has a method, use [`ClassInfo::hasMethod`](https://github.com/silverstripe/silverstripe-framework/blob/714386154917263a4ded142c6682acdde46d4220/src/Core/ClassInfo.php#L402) instead of the native `method_exists` PHP method. `ClassInfo::hasMethod` will account for things like extensions and so on.
