### ISSUE TITLE
Popover field does not get dismissed when you click out of it

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-elemental#876]
When you click out of the Popover field, it should dismiss the field. This use to work in the 4.6 release, but doesn't in the 4.7 release.

https://youtu.be/OSELa0MwGX8

**Comment by maxime-rainville** [comment]
@silverstripeux

**Comment by Cheddam** [comment]
Fixed in silverstripe/silverstripe-admin#1181.
