### ISSUE TITLE
Provide duplicate option for non-inline blocks

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-elemental#881]
Currently we only provide the duplicate option for a what is often referred to as an "inline block" (can edit on page). Because many blocks are still managed "non-inline" there is a very drawn-out process to duplicate these items (e.g. opening CMS in 2 tabs and copy-pasting to a new block) which are more prone to system and user errors.

The experience should align to inline block duplicate flow where possible and take into consideration user permissions can-edit etc.

Related: https://github.com/silverstripe/silverstripe-elemental/pull/770#issuecomment-789339111

**Comment by jellygnite** [comment]
Is there a timeline of when this feature might be available? i.e. duplicate blocks that are managed as 'non-inline'. Or has anyone managed to get this to work with a gridfieldaction?

**Comment by brynwhyman** [comment]
@clarkepaul what do you think about adding the 'action toggle' to non-inline editable blocks? I'm assuming there was an explicit decision to not include them, but all of the options still seem relevant even if a block is not inline editable?

I.e
![image](https://user-images.githubusercontent.com/15868440/123709410-28385400-d8c1-11eb-91eb-b51134e6cc73.png)

**Comment by clarkepaul** [comment]
> I'm assuming there was an explicit decision to not include them, but all of the options still seem relevant even if a block is not inline editable?

I don't think there was any decisions made to exclude these actions, it was only that we only focused on the core 4 default blocks so no (or less) effort was put to into extending functionality to the base block.
@brynwhyman yes, thats exactly where its intended to be, no different from the non-inline experience. The same actions seem relevant and potentially any other tabs from inside those blocks could be surfaced into the top set of actions as direct links (that would be a bonus).

**Comment by clarkepaul** [comment]
I think what we are missing is the issue to provide the same set of actions and navigation for non-inline blocks rather than focusing on just the duplicate functionality. Will open another issue...

**Comment by brynwhyman** [comment]
We're going to implement this in https://github.com/silverstripe/silverstripe-elemental/issues/512

**Comment by GuySartorelli** [comment]
This was implemented in #512.
