### ISSUE TITLE
Fix behat failure screenshots

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/silverstripe-elemental#886]
Since this module was moved to the Silverstripe organisation, the TravisCI builds are not saving screenshots in the correct place, should a behat failure occur.

We have a documented process for having the screenshots uploaded to a dedicated S3 bucket when there's a failure on a branch. This issue covers the work is resolving this.

@emteknetnz knows where the process is documented.

**Comment by emteknetnz** [comment]
The S3 secrets in

https://travis-ci.com/github/silverstripe/silverstripe-elemental/settings

Should match

https://travis-ci.com/github/silverstripe/silverstripe-asset-admin/settings

Secrets are probably stored in the usual location
