### ISSUE TITLE
Don't break if the class is missing

### ISSUE THREAD

**Issue by lbradley-mm** [silverstripe/silverstripe-elemental#888]
If the associated class is removed then causes `Uncaught Exception SilverStripe\Core\Injector\InjectorNotFoundException: "ReflectionException: Class ***** does not exist in` error

https://github.com/silverstripe/silverstripe-elemental/blob/266dc9511e81bdda7006ccd2918875f693b805bd/src/Models/ElementalArea.php#L199-L204

Not sure on how best to handle this
Maybe check ALL elements that use an `ElementalArea` association and then re-save to fix

**Comment by emteknetnz** [comment]
That seems a bit odd.  There's a `ClassInfo::exists($class)` check right before `Injector::inst()->get($class)`.  How does this manage to break?

**Comment by GuySartorelli** [comment]
Just to be sure, was the site cache flushed after the class was removed?

**Comment by michalkleiner** [comment]
Not sure if it's the same problem, but I just encountered an elemental area disappearing completely from the CMS when an element class (extending BaseElement) gets removed while the content is still in the database. With pages, the CMS handles that gracefully and displays a warning that the page type is obsolete and will be changed on the next save, with elements the whole area doesn't render at all, even for the valid elements.

**Comment by GuySartorelli** [comment]
@michalkleiner That's documented in #708 but you're right, the two issues are probably the same.

I do have a build task I wrote to handle this problem - let me know if that would be useful and I'll make a repo for it and link it in a comment for #708.

**Comment by michalkleiner** [comment]
@GuySartorelli yep, it's #708 exactly. Thanks for the offer, we don't need a task to fix the data, when I found what the problem was I could deal with it.

**Comment by GuySartorelli** [comment]
Closed in favor of #708
