### ISSUE TITLE
Form field attributes are not applied if inline_editable: true

### ISSUE THREAD

**Issue by jellygnite** [silverstripe/silverstripe-elemental#891]
I wanted to apply a ```data-attribute="something"``` to some form fields on an Element but noticed these don't get added when the Element has inline_editable set to true.

Is this intentional?

It looks like the React component just isn't rendering the attributes. For now I have just set all my Elements to inline_editable: false but it would be great if data-attributes were applied on the inline forms.

**Comment by lerni** [comment]
duplicate https://github.com/silverstripe/silverstripe-elemental/issues/738
yeah this is the #one reason I keep roll-out elements with inline_editable: false

**Comment by kinglozzer** [comment]
Thanks both! Will close as a duplicate of https://github.com/silverstripe/silverstripe-elemental/issues/738
