### ISSUE TITLE
Menu is partially not visible in split mode

### ISSUE THREAD

**Issue by ovogel-wigital** [silverstripe/silverstripe-elemental#900]
When I open the menu in CMS to add a new block, the menu is shifted and goes beyond the left edge of the browser window. This only happens in split mode in edit mode everything seems fine.

Version: 4.5.0

Tested in: Firefox 88 and Chrome 90

![bug](https://user-images.githubusercontent.com/60091414/117441002-14ade400-af35-11eb-915b-33eb71c38c20.png)

**Comment by ovogel-wigital** [comment]
The issue seems to be related to the number of items in the menu. The more elements are listed, the wider the menu becomes. (See examples below.)

I could exclude external CSS or JavaScripts as error sources.

### 6 items in menu
![6_items](https://user-images.githubusercontent.com/60091414/117618917-e7e51100-b16e-11eb-8735-0432bbce5e2e.png)

### 8 items in menu
![8_items](https://user-images.githubusercontent.com/60091414/117618938-ed425b80-b16e-11eb-8f1b-e7aea0536f9e.png)

### 10 items in menu
![10_items](https://user-images.githubusercontent.com/60091414/117618956-f2070f80-b16e-11eb-9c26-ed121d6070c4.png)

**Comment by ovogel-wigital** [comment]
I don't know why but I just updated SilverStripe from 4.7.2 to 4.7.3 and now the menu works as expected.

**Comment by lerni** [comment]
At some point (probable with 4.7.*) I've used custom styles for `.popover.show` - but have removed it since. Duno where or what changes fixed it. But this is the reason why I tried to replicate... since it looks fixed now, can this be closed?
