### ISSUE TITLE
CMS preview doesn't work for non-inline-editable blocks (hasn't for a while)

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/silverstripe-elemental#905]
I've just recently discovered that older versions of this module included a CMS preview panel when editing non-inline-editable blocks. Considering there's still a lot of code in BaseElement that refers to this, I think it's supposed to still be working?
A git bisect shows that the preview panel hasn't actually been present since [281a9e9132625d68845dfc9be0e9103c106b5c81](https://github.com/silverstripe/silverstripe-elemental/commit/281a9e9132625d68845dfc9be0e9103c106b5c81).

I tried just slapping `implements CMSPreviewable` back on the `BaseElement` class but it seems there have been enough changes since this was last working that that isn't enough to bring back the preview pane.

Am I just missing some configuration setting somewhere or does this just not work?
And further on that, is it _meant_ to work? Or should the code that refers to it be removed?

## ACs
- A preview of the block's parent page is shown when in the edit view of a non-inline block

**Comment by GuySartorelli** [comment]
I've looked into this a bit and it seems that there are two things missing:

Part of the problem is with GridFieldDetailForm_ItemRequest in silverstripe/silverstripe-framework which doesn't include the `cms-previewable` extraClass on the form, nor the `SilverStripeNavigator` field - both of which are added to normal edit forms in `LeftAndMain`.

The other part is that _even if those were included_, the following two config variables aren't set in the `BaseElement` class:
```
private static $show_stage_link = true;
private static $show_live_link = true;
```

**Comment by GuySartorelli** [comment]
The former has been raised in silverstripe/silverstripe-cms#2659 (since that's the module that adds those parts to normal edit forms) but this issue is to track adding the necessary config variables to `BaseElement` (or alternatively an explicit decision to not do that - but perhaps updating docs?)

**Comment by emteknetnz** [comment]
I think the reason that non-inline editable block are not previewable when editing is because you are taken to a Block edit form `/admin/pages/edit/EditForm/6/field/ElementalArea/item/2/edit` which does not contain a preview panel, rather than the Page edit form `/admin/pages/edit/show/6` which does have a preview panel

Changes made to the non-inline editable block are still previewable from the page edit form

I've uploaded a video demonstrating this https://www.youtube.com/watch?v=bW1NbKQWxp0

I don't think there needs to be any changes made here so I'll mark this as closed.  @clarkepaul @brynwhyman you may have a different perspective on this, if so then please add a comment below.

**Comment by GuySartorelli** [comment]
@emteknetnz Per my previous comment (quoted again here) even if the "Block edit form" (which is handled with a `GridFieldDetailForm`) does get amended to include the preview panel, which I've raised a ticket for but could be done in a given project through `Extension` classes, this module still does need some changes:

> The other part is that even if those were included, the following two config variables aren't set in the BaseElement class:
> 
> `private static $show_stage_link = true;`
> `private static $show_live_link = true;`
> and the CMSPreviewable interface does need to be implemented.

**Comment by maxime-rainville** [comment]
There's a [doc article about enabling previews](https://docs.silverstripe.org/en/4/developer_guides/customising_the_admin_interface/preview/). I suspect it's horribly outdated however, but it could be a starting point.
