### ISSUE TITLE
Solr search not working on CWP 2.8.0-rc1

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-elemental#907]
**Setup**
- Tested on CWP In-nation with recipe-kitchen-sink 2.8.0-rc1
- The deployed code bundle has no special config in relation to fulltextsearch or elemental - according to docs, it shouldn't need any https://github.com/silverstripe/silverstripe-elemental/blob/4/docs/en/searching-blocks.md#usage
- Page/PageController extend the CWP BasePage/BasePageController
- Solr configure was run

**Replication:**
- I have a BlockPage with a Content Block with the text "The quick brown fox jumps over the lazy dog"
- Publish the page
- Search on the frontend for the phrase "quick brown fox" said "Missed. Try again." - This text maps to Site Settings > Search Options > Text to display when there are no results

An equivalent search for regular non-block page content did yield expected results

**Comment by michalkleiner** [comment]
I believe the Elemental-specific solr index was removed as it was actually added just for testing way back when, can you clarify that @chillu (I think we had a chat about it at some point in past, unless I'm confusing it with something else)?

**Comment by emteknetnz** [comment]
I'd say this is probably misconfiguration from our end for the test bundle used.  

Adding the following (copied from ElementalSolrIndex) to deafult CwpSolrIndex will fix this issue locally

`$this->addFulltextField('ElementsForSearch');`
