### ISSUE TITLE
Custom Element Template Can Not Be Found Unless it is in the Template Root Directory

### ISSUE THREAD

**Issue by dajeinc** [silverstripe/silverstripe-elemental#908]
If I use a file structure like

/themes/my_theme/templates/elements/MyCustomElement.ss

the file will not be found

I have to put all Element.ss files in the root template directory

/themes/my_theme/templates/MyCustomElement.ss

Is this a Silverstripe issue or Elemental issue?

Is there a way to make SS find the element templates in a designated directory.

**Comment by emteknetnz** [comment]
Template files need to be in directories that match the namespacing of the class they're rendering

e.g. 
/DNADesign/Elemental/Models/ElementContent.ss

https://github.com/silverstripe/silverstripe-elemental/blob/4/templates/DNADesign/Elemental/Models/ElementContent.ss

If you're still stuck, then a good place to get support is on the [Silverstripe community slack channel](http://silverstripe.org/slack).
