### ISSUE TITLE
add index on sort for faster sorting

### ISSUE THREAD

**Issue by sunnysideup** [silverstripe/silverstripe-elemental#915]
Adding an index on the `Sort` field will make retrieval faster.

**Comment by emteknetnz** [comment]
PR welcome

**Comment by brynwhyman** [comment]
Here you go @emteknetnz ;) https://github.com/silverstripe/silverstripe-elemental/pull/916

**Comment by GuySartorelli** [comment]
#916 was closed without being merged, unfortunately. It's a nice quick change to make so I've raised a new one with just the sort index change.

**Comment by GuySartorelli** [comment]
Nevermind, #919 beat me to it and has been merged in.
Someone should close this ticket before a fourth PR is raised :p
