### ISSUE TITLE
Validation error doesn't surface on Title field

### ISSUE THREAD

**Issue by andrewandante** [silverstripe/silverstripe-elemental#945]
`BaseElement` combines `Title` and `ShowTitle` into one instance of `TextCheckboxGroupField`. If you require this field, and don't fill it out, the element will throw a Validation Error but not show you where - seems to be hidden by combining the fields.

**Comment by lerni** [comment]
Just ran into this. If `inline_editable` is enabled, it even ignores the required field :disappointed: Setting a Title is essential for the use with [dnadesign/silverstripe-elemental-virtual](https://github.com/dnadesign/silverstripe-elemental-virtual) but ATM it looks like you cannot make Title a required field.

**Comment by michalkleiner** [comment]
Increasing the impact to accommodate not being able to require the field when inline editable.

**Comment by GuySartorelli** [comment]
@michalkleiner fyi the lack of validation for inline editable blocks is already raised separately in #699

**Comment by maxime-rainville** [comment]
I don't see any scenario where we fix this without fixing https://github.com/silverstripe/silverstripe-elemental/issues/329

I'm going to call this one a duplicate.
