### ISSUE TITLE
Invariant package JS warning on page publish

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-elemental#950]
![image](https://user-images.githubusercontent.com/4809037/143320613-6e052607-cc20-41e3-911a-ce35c88d0144.png)

I don't think this is having an end user impact?

Link goes to here https://github.com/apollographql/invariant-packages

Likely a side-effect from https://github.com/silverstripe/silverstripe-elemental/pull/949, or one of the other upgrade JS pull-requests that happened recently

## Acceptance criteria
- [ ] The console warning is squash.
- [ ] If the connection drops, you don't end up with an infinite loop.

## PRs
- https://github.com/silverstripe/silverstripe-elemental/pull/1015

**Comment by GuySartorelli** [comment]
Closing in favour of https://github.com/silverstripe/silverstripe-elemental/issues/1158
