### ISSUE TITLE
Inline actions broken in GraphQL4

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-elemental#954]
Inline unpublish action (via the 3 dots icon) causes the following error in GraphQL4 only

![image](https://user-images.githubusercontent.com/4809037/150064338-6bf51bc4-65b6-4738-8dcd-7d8769603aa2.png)

Travis
https://app.travis-ci.com/github/silverstripe/silverstripe-elemental/jobs/556073834

```
--- Failed scenarios:
    tests/Behat/features/archive-block-element.feature:23
    tests/Behat/features/publish-block-element.feature:23
    tests/Behat/features/unpublish-block-element.feature:23
```

**Comment by unclecheese** [comment]
Fix is here https://github.com/silverstripe/silverstripe-graphql/pull/431

**Comment by unclecheese** [comment]
And here https://github.com/silverstripe/silverstripe-elemental/pull/955
