### ISSUE TITLE
Create db migration task for v3 -> 4

### ISSUE THREAD

**Issue by pitchandtone** [silverstripe/silverstripe-elemental#97]
Probably use something like: https://github.com/dnadesign/silverstripe-migraterelations

**Comment by nicolewilliams16** [comment]
I've removed this from the 2.0.0 milestone, we'll consider adding the migration tools post must-haves for 2.0.0

**Comment by wernerkrauss** [comment]
I created a module for this: https://github.com/wernerkrauss/elemental-migration

**Comment by GuySartorelli** [comment]
I don't think this is really necessary anymore - and if it is, there's a module linked above. Closing this issue.
