### ISSUE TITLE
Publish block button doesn't work. Version 4.8

### ISSUE THREAD

**Issue by sabina-talipova** [silverstripe/silverstripe-elemental#970]
In 4.8 version: When user click on Publish button in Block Dropdown menu and send request, server returns error:
`"Cannot query field \"publishBlock\" on type \"Mutation\". Did you mean \"publishFiles\"?"`

![publish_button.png](https://images.zenhubusercontent.com/6240ee9a7a0aac6d45cfd39d/21a3d022-1ca7-4d60-b139-65b8002206f3)

Travis : https://app.travis-ci.com/github/silverstripe/silverstripe-elemental/builds/249111248

**Comment by GuySartorelli** [comment]
Note that this is currently specifically when using graphql v4, which has not yet had a stable release.
