### ISSUE TITLE
Archive button doesn't work. Version 4.8

### ISSUE THREAD

**Issue by sabina-talipova** [silverstripe/silverstripe-elemental#971]
In version 4.8. 
When user clicks on Archive button in block dropdown menu, server returns 500 error with 
`[Emergency] Uncaught TypeError: Argument 1 passed to GraphQL\Type\Definition\Type::getNullableType() must be an instance of GraphQL\Type\Definition\Type, null given`.

In payload: `'{
"operationName":"ArchiveBlock"
"query":"mutation ArchiveBlock($blockId: ID!) {\\n  deleteBlocks(ids: [$blockId])\\n}\\n"
"variables":{"blockId":"55"},"blockId":"55"
}'`

![archive_button.png](https://images.zenhubusercontent.com/6240ee9a7a0aac6d45cfd39d/91f1dbbf-fab3-4345-9307-463cb0e5e25e)

Travis: https://app.travis-ci.com/github/silverstripe/silverstripe-elemental/builds/249111248

**Comment by thomaspaulson** [comment]
works fine for me 

![Screenshot from 2022-04-08 11-18-06](https://user-images.githubusercontent.com/1735777/162372738-3cb2cdee-113d-4f7c-bc3a-a707e2cf4948.png)

**Comment by lerni** [comment]
Does it work on ElementContent and break on custom Elements? AFAIR you need to add some JS to make it also work on custom Elements, but cannot find docs for this.

**Comment by sabina-talipova** [comment]
In version 4.8 there are a failing behat tests for PHP 8 build in Travis, but passing PHP 7.4. My local env has PHP 7.4. I see this issue when I'm testing Elemental Area manually in my local environment. Both, Custom element and Content element fail tests. I'll keep going to test to sort it out.

**Comment by GuySartorelli** [comment]
Note that this is currently specifically when using graphql v4, which has not yet had a stable release.
