### ISSUE TITLE
PHP 8.1 support

### ISSUE THREAD

**Issue by TomOudeRengerink** [silverstripe/silverstripe-elemental#988]
Any plans on making elemental compatible with PHP 8.1? PHP 8.1 is available since SilverStripe 4.11.

**Comment by michalkleiner** [comment]
Is it not working already? Any errors when you run on PHP 8.1?

**Comment by emteknetnz** [comment]
@TomOudeRengerink [4.9.0](https://github.com/silverstripe/silverstripe-elemental/releases/tag/4.9.0) support PHP 8.1

Please let us know if you experience any issues
